// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddFriendRequest struct {
	UserId       uint          `header:"User-Id"`
	FriendId     uint          `json:"friend_id"`              // 好友ID
	AuthMessage  string        `json:"auth,optional"`          // 验证消息
	AuthQuestion *AuthQuestion `json:"auth_question,optional"` // 验证问题
}

type AddFriendResponse struct {
}

type AuthQuestion struct {
	Problem1 *string `json:"problem1,optional"`
	Problem2 *string `json:"problem2,optional"`
	Problem3 *string `json:"problem3,optional"`
	Answer1  *string `json:"answer1,optional"`
	Answer2  *string `json:"answer2,optional"`
	Answer3  *string `json:"answer3,optional"`
}

type FriendAuthInfo struct {
	UserId       uint          `json:"user_id"`
	Name         string        `json:"name"`
	Avatar       string        `json:"avatar"`
	AuthMessage  string        `json:"auth,optional"`          // 验证消息
	AuthQuestion *AuthQuestion `json:"auth_question,optional"` // 验证问题
	Status       int8          `json:"status"`
	Auth         int8          `json:"auth"` // 好友验证
	Id           uint          `json:"id"`
	Flag         string        `json:"flag"` // send  rev
}

type FriendAuthRequest struct {
	UserId uint `header:"User-Id"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
}

type FriendAuthResponse struct {
	List  []FriendAuthInfo `json:"list"`
	Total int64            `json:"total"`
}

type FriendAuthStatusRequest struct {
	UserId uint `header:"User-Id"`
	AuthId uint `json:"auth_id"`
	Status int8 `json:"status"`
}

type FriendAuthStatusResponse struct {
	UserId uint `header:"User-Id"`
	AuthId uint `json:"auth_id"`
}

type FriendDeleteRequest struct {
	UserId   uint `header:"User-Id"`
	FriendId uint `json:"friend_id"` // 好友ID
}

type FriendDeleteResponse struct {
}

type FriendInfoRequest struct {
	UserId   uint `header:"User-Id"`
	Role     int8 `header:"Role"`
	FriendId uint `form:"friend_id"` // 好友ID
}

type FriendInfoResponse struct {
	UserId   uint   `json:"user_id"`
	Name     string `json:"name"`
	Sign     string `json:"sign"`
	Avatar   string `json:"avatar"`
	Notice   string `json:"notice"`    // 备注
	IsOnline bool   `json:"is_online"` // 是否在线
}

type FriendListRequest struct {
	UserId uint `header:"User-Id"`
	Role   int8 `header:"Role"`
	Page   int  `form:"page,optional"`
	Limit  int  `form:"limit,optional"`
}

type FriendListResponse struct {
	List  []FriendInfoResponse `json:"list"`
	Total int64                  `json:"total"`
}

type FriendNoticeUpdateRequest struct {
	UserId   uint   `header:"User-Id"`
	FriendId uint   `json:"friend_id"` // 好友ID
	Notice   string `json:"notice"`    // 备注
}

type FriendNoticeUpdateResponse struct {
}

type SearchInfo struct {
	UserId   uint   `json:"user_id"`
	Name     string `json:"name"`
	Sign     string `json:"sign"`
	Avatar   string `json:"avatar"`
	IsFriend bool   `json:"is_friend"`
}

type SearchRequest struct {
	UserId uint   `header:"User-Id"`
	Key    string `form:"key"`
	Online bool   `form:"online,optional"`
	Page   int    `form:"page,optional"`
	Limit  int    `form:"limit,optional"`
}

type SearchResponse struct {
	List  []SearchInfo `json:"list"`
	Total int64        `json:"total"`
}

type UserAuthRequest struct {
	UserId   uint `header:"User-Id"`
	FriendId uint `json:"friend_id"` // 好友ID
}

type UserAuthResponse struct {
	Auth         int8         `json:"auth"`                   // 好友验证
	AuthQuestion AuthQuestion `json:"auth_question,optional"` // 验证问题
}

type UserInfoRequest struct {
	UserId uint `header:"User-Id"`
	Role   int8 `header:"Role"`
}

type UserInfoResponse struct {
	UserId        uint          `json:"user_id"`
	Name          string        `json:"name"`
	Sign          string        `json:"sign"`
	Avatar        string        `json:"avatar"`
	RecallMessage *string       `json:"recall_message"` // 撤回消息内容
	FriendOnline  bool          `json:"friend_online"`  // 好友上线
	Sound         bool          `json:"sound"`          // 好友上线声音
	SecureLink    bool          `json:"secure_link"`    // 安全链接
	SavePassword  bool          `json:"save_password"`  // 保存密码
	SearchUser    int8          `json:"search_user"`    // 别人查找到你的方式
	Auth          int8          `json:"auth"`           // 好友验证
	AuthQuestion  *AuthQuestion `json:"auth_question"`  // 验证问题
}

type UserUpdateRequest struct {
	UserId        uint          `json:"user_id"`
	Name          *string       `json:"name,optional"`
	Sign          *string       `json:"sign,optional"`
	Avatar        *string       `json:"avatar,optional"`
	RecallMessage *string       `json:"recall_message,optional"` // 撤回消息内容
	FriendOnline  *bool         `json:"friend_online,optional"`  // 好友上线
	Sound         *bool         `json:"sound,optional"`          // 好友上线声音
	SecureLink    *bool         `json:"secure_link,optional"`    // 安全链接
	SavePassword  *bool         `json:"save_password,optional"`  // 保存密码
	SearchUser    *int8         `json:"search_user,optional"`    // 别人查找到你的方式
	Auth          *int8         `json:"auth,optional"`           // 好友验证
	AuthQuestion  *AuthQuestion `json:"auth_question,optional"`  // 验证问题
}

type UserUpdateResponse struct {
}
