// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"fim_server/service/api/chat/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(src *rest.Server, serverCtx *svc.ServiceContext) {
	src.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/api/chat/chat",
				Handler: ChatDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/history",
				Handler: ChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/session",
				Handler: ChatSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/user_top",
				Handler: UserTopHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/ws/chat",
				Handler: ChatWebsocketHandler(serverCtx),
			},
		},
	)
}
