// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	admin "fim_server/service/api/chat/internal/handler/admin"
	"fim_server/service/api/chat/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(src *rest.Server, serverCtx *svc.ServiceContext) {
	src.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/api/chat/chat",
				Handler: ChatDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/history",
				Handler: ChatHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/session",
				Handler: ChatSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/user_top",
				Handler: UserTopHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/ws/chat",
				Handler: ChatWebsocketHandler(serverCtx),
			},
		},
	)

	src.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/chat/admin/history",
					Handler: admin.ChatHistoryAdminHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/chat/admin/history",
					Handler: admin.ChatHistoryDeleteAdminHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/chat/admin/session",
					Handler: admin.ChatSessionAdminHandler(serverCtx),
				},
			}...,
		),
	)
}
