// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: file.proto

package server

import (
	"context"

	"fim_server/service/rpc/file/file_rpc"
	"fim_server/service/rpc/file/internal/logic/file"
	"fim_server/service/rpc/file/internal/svc"
)

type FileServer struct {
	svcCtx *svc.ServiceContext
	file_rpc.UnimplementedFileServer
}

func NewFileServer(svcCtx *svc.ServiceContext) *FileServer {
	return &FileServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServer) FileInfo(ctx context.Context, in *file_rpc.FileInfoRequest) (*file_rpc.FileInfoResponse, error) {
	l := filelogic.NewFileInfoLogic(ctx, s.svcCtx)
	return l.FileInfo(in)
}
