// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"

	"fim_server/service/rpc/user/internal/logic/friend"
	"fim_server/service/rpc/user/internal/svc"
	"fim_server/service/rpc/user/user_rpc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServer) IsFriend(ctx context.Context, in *user_rpc.IsFriendRequest) (*user_rpc.Empty, error) {
	l := friendlogic.NewIsFriendLogic(ctx, s.svcCtx)
	return l.IsFriend(in)
}

func (s *FriendServer) FriendList(ctx context.Context, in *user_rpc.ID) (*user_rpc.FriendListResponse, error) {
	l := friendlogic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}
