// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type FileRequest struct {
	UserId uint `header:"User-Id"`
}

type FileResponse struct {
	Src string `json:"src"`
}

type ShowRequest struct {
	Name string `path:"name"`
}

type ShowResponse struct {
	Url string `json:"url"`
}
