// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: group.proto

package server

import (
	"context"

	"fim_server/service/rpc/group/group_rpc"
	"fim_server/service/rpc/group/internal/logic"
	"fim_server/service/rpc/group/internal/svc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group_rpc.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServer) IsInGroupMember(ctx context.Context, in *group_rpc.IsInGroupMemberRequest) (*group_rpc.IsInGroupMemberResponse, error) {
	l := logic.NewIsInGroupMemberLogic(ctx, s.svcCtx)
	return l.IsInGroupMember(in)
}
