// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AuthenticationRequest struct {
	Token     string `header:"Token,optional"`
	ValidPath string `header:"ValidPath,optional"`
}

type AuthenticationResponse struct {
	UserId uint64 `json:"user_id"`
	Role   int32  `json:"role"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type OpenLoginInfoResponse struct {
	Username string `json:"username"`
	Icon     string `json:"icon"`
	Href     string `json:"href"` // 跳转地址
}

type OpenLoginRequest struct {
	Code string `json:"code"`
	Flag string `json:"flag"`
}
