// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.0
// source: rpc/chat.proto

package chat_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendUserId    uint32 `protobuf:"varint,1,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	ReceiveUserId uint32 `protobuf:"varint,2,opt,name=receive_user_id,json=receiveUserId,proto3" json:"receive_user_id,omitempty"`
	Message       []byte `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                  // message json格式
	SystemMessage []byte `protobuf:"bytes,4,opt,name=system_message,json=systemMessage,proto3" json:"system_message,omitempty"` // 系统消息
}

func (x *UserChatRequest) Reset() {
	*x = UserChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatRequest) ProtoMessage() {}

func (x *UserChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatRequest.ProtoReflect.Descriptor instead.
func (*UserChatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{0}
}

func (x *UserChatRequest) GetSendUserId() uint32 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *UserChatRequest) GetReceiveUserId() uint32 {
	if x != nil {
		return x.ReceiveUserId
	}
	return 0
}

func (x *UserChatRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UserChatRequest) GetSystemMessage() []byte {
	if x != nil {
		return x.SystemMessage
	}
	return nil
}

type UserChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserChatResponse) Reset() {
	*x = UserChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatResponse) ProtoMessage() {}

func (x *UserChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatResponse.ProtoReflect.Descriptor instead.
func (*UserChatResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{1}
}

func (x *UserChatResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserListChatTotalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIdList []uint32 `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
}

func (x *UserListChatTotalRequest) Reset() {
	*x = UserListChatTotalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListChatTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListChatTotalRequest) ProtoMessage() {}

func (x *UserListChatTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListChatTotalRequest.ProtoReflect.Descriptor instead.
func (*UserListChatTotalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{2}
}

func (x *UserListChatTotalRequest) GetUserIdList() []uint32 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type ChatTotalMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendMessageTotal    int32 `protobuf:"varint,1,opt,name=send_message_total,json=sendMessageTotal,proto3" json:"send_message_total,omitempty"`
	ReceiveMessageTotal int32 `protobuf:"varint,2,opt,name=receive_message_total,json=receiveMessageTotal,proto3" json:"receive_message_total,omitempty"`
}

func (x *ChatTotalMessage) Reset() {
	*x = ChatTotalMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatTotalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTotalMessage) ProtoMessage() {}

func (x *ChatTotalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTotalMessage.ProtoReflect.Descriptor instead.
func (*ChatTotalMessage) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatTotalMessage) GetSendMessageTotal() int32 {
	if x != nil {
		return x.SendMessageTotal
	}
	return 0
}

func (x *ChatTotalMessage) GetReceiveMessageTotal() int32 {
	if x != nil {
		return x.ReceiveMessageTotal
	}
	return 0
}

type UserListChatTotalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[uint32]*ChatTotalMessage `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UserListChatTotalResponse) Reset() {
	*x = UserListChatTotalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListChatTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListChatTotalResponse) ProtoMessage() {}

func (x *UserListChatTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListChatTotalResponse.ProtoReflect.Descriptor instead.
func (*UserListChatTotalResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chat_proto_rawDescGZIP(), []int{4}
}

func (x *UserListChatTotalResponse) GetResult() map[uint32]*ChatTotalMessage {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_rpc_chat_proto protoreflect.FileDescriptor

var file_rpc_chat_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x22, 0x9c, 0x01, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x74, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x32, 0x0a, 0x15, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xbb, 0x01, 0x0a, 0x19, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x1a, 0x55, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xa7, 0x01, 0x0a, 0x04, 0x43, 0x68, 0x61,
	0x74, 0x12, 0x41, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x12, 0x19, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_chat_proto_rawDescOnce sync.Once
	file_rpc_chat_proto_rawDescData = file_rpc_chat_proto_rawDesc
)

func file_rpc_chat_proto_rawDescGZIP() []byte {
	file_rpc_chat_proto_rawDescOnce.Do(func() {
		file_rpc_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_chat_proto_rawDescData)
	})
	return file_rpc_chat_proto_rawDescData
}

var file_rpc_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_chat_proto_goTypes = []interface{}{
	(*UserChatRequest)(nil),           // 0: user_rpc.UserChatRequest
	(*UserChatResponse)(nil),          // 1: user_rpc.UserChatResponse
	(*UserListChatTotalRequest)(nil),  // 2: user_rpc.UserListChatTotalRequest
	(*ChatTotalMessage)(nil),          // 3: user_rpc.ChatTotalMessage
	(*UserListChatTotalResponse)(nil), // 4: user_rpc.UserListChatTotalResponse
	nil,                               // 5: user_rpc.UserListChatTotalResponse.ResultEntry
}
var file_rpc_chat_proto_depIdxs = []int32{
	5, // 0: user_rpc.UserListChatTotalResponse.result:type_name -> user_rpc.UserListChatTotalResponse.ResultEntry
	3, // 1: user_rpc.UserListChatTotalResponse.ResultEntry.value:type_name -> user_rpc.ChatTotalMessage
	0, // 2: user_rpc.Chat.UserChat:input_type -> user_rpc.UserChatRequest
	2, // 3: user_rpc.Chat.UserListChatTotal:input_type -> user_rpc.UserListChatTotalRequest
	1, // 4: user_rpc.Chat.UserChat:output_type -> user_rpc.UserChatResponse
	4, // 5: user_rpc.Chat.UserListChatTotal:output_type -> user_rpc.UserListChatTotalResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_chat_proto_init() }
func file_rpc_chat_proto_init() {
	if File_rpc_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListChatTotalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatTotalMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListChatTotalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_chat_proto_goTypes,
		DependencyIndexes: file_rpc_chat_proto_depIdxs,
		MessageInfos:      file_rpc_chat_proto_msgTypes,
	}.Build()
	File_rpc_chat_proto = out.File
	file_rpc_chat_proto_rawDesc = nil
	file_rpc_chat_proto_goTypes = nil
	file_rpc_chat_proto_depIdxs = nil
}
