// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: group.proto

package group

import (
	"context"

	"fim_server/service/rpc/group/group_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResponse           = group_rpc.EmptyResponse
	GroupMemberListRequest  = group_rpc.GroupMemberListRequest
	IsInGroupMemberRequest  = group_rpc.IsInGroupMemberRequest
	UserGroupSearchRequest  = group_rpc.UserGroupSearchRequest
	UserGroupSearchResponse = group_rpc.UserGroupSearchResponse

	Group interface {
		IsInGroupMember(ctx context.Context, in *IsInGroupMemberRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
		UserGroupSearch(ctx context.Context, in *UserGroupSearchRequest, opts ...grpc.CallOption) (*UserGroupSearchResponse, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

func (m *defaultGroup) IsInGroupMember(ctx context.Context, in *IsInGroupMemberRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.IsInGroupMember(ctx, in, opts...)
}

func (m *defaultGroup) UserGroupSearch(ctx context.Context, in *UserGroupSearchRequest, opts ...grpc.CallOption) (*UserGroupSearchResponse, error) {
	client := group_rpc.NewGroupClient(m.cli.Conn())
	return client.UserGroupSearch(ctx, in, opts...)
}
