// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: setting.proto

package setting

import (
	"context"

	"fim_server/service/rpc/setting/setting_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty               = setting_rpc.Empty
	SettingInfoResponse = setting_rpc.SettingInfoResponse

	Setting interface {
		SettingInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SettingInfoResponse, error)
	}

	defaultSetting struct {
		cli zrpc.Client
	}
)

func NewSetting(cli zrpc.Client) Setting {
	return &defaultSetting{
		cli: cli,
	}
}

func (m *defaultSetting) SettingInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SettingInfoResponse, error) {
	client := setting_rpc.NewSettingClient(m.cli.Conn())
	return client.SettingInfo(ctx, in, opts...)
}
