// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"

	"fim_server/service/rpc/user/internal/logic/usercurtail"
	"fim_server/service/rpc/user/internal/svc"
	"fim_server/service/rpc/user/user_rpc"
)

type UserCurtailServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUserCurtailServer
}

func NewUserCurtailServer(svcCtx *svc.ServiceContext) *UserCurtailServer {
	return &UserCurtailServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCurtailServer) IsCurtail(ctx context.Context, in *user_rpc.ID) (*user_rpc.CurtailResponse, error) {
	l := usercurtaillogic.NewIsCurtailLogic(ctx, s.svcCtx)
	return l.IsCurtail(in)
}
