// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package usercurtail

import (
	"context"

	"fim_server/service/rpc/user/user_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CurtailResponse        = user_rpc.CurtailResponse
	Empty                  = user_rpc.Empty
	FriendListResponse     = user_rpc.FriendListResponse
	ID                     = user_rpc.ID
	IdList                 = user_rpc.IdList
	IsFriendRequest        = user_rpc.IsFriendRequest
	UserCreateRequest      = user_rpc.UserCreateRequest
	UserCreateResponse     = user_rpc.UserCreateResponse
	UserInfo               = user_rpc.UserInfo
	UserInfoResponse       = user_rpc.UserInfoResponse
	UserOnlineListResponse = user_rpc.UserOnlineListResponse

	UserCurtail interface {
		IsCurtail(ctx context.Context, in *ID, opts ...grpc.CallOption) (*CurtailResponse, error)
	}

	defaultUserCurtail struct {
		cli zrpc.Client
	}
)

func NewUserCurtail(cli zrpc.Client) UserCurtail {
	return &defaultUserCurtail{
		cli: cli,
	}
}

func (m *defaultUserCurtail) IsCurtail(ctx context.Context, in *ID, opts ...grpc.CallOption) (*CurtailResponse, error) {
	client := user_rpc.NewUserCurtailClient(m.cli.Conn())
	return client.IsCurtail(ctx, in, opts...)
}
